name:                husk-prelude
version:             0.1.0.0
github:              "aleshgo/husk-prelude"
license:             BSD3
author:              "Oleksii Zhuravlov"
maintainer:          "Oleksii Zhuravlov <aleshgo@gmail.com>"
copyright:           "2019 Oleksii Zhuravlov"
synopsis:            Yet another core prelude.
description:         A prelude built on standard prelude.
category:            Prelude, Library
stability:           Experimental

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- string-conversions

library:
  source-dirs: src

tests:
  husk-prelude-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - husk-prelude
    - hspec
